#include "rbyinfo.h"
#include "rbyid.h"

#define TYPE_NORMAL 0
#define TYPE_FIGHTING 1
#define TYPE_FLYING 2
#define TYPE_POISON 3
#define TYPE_GROUND 4
#define TYPE_ROCK 5
#define TYPE_BIRD 6
#define TYPE_BUG 7
#define TYPE_GHOST 8
#define TYPE_FIRE 20
#define TYPE_WATER 21
#define TYPE_GRASS 22
#define TYPE_ELECTRIC 23
#define TYPE_PSYCHIC 24
#define TYPE_ICE 25
#define TYPE_DRAGON 26

static Info items[256] =
{
	[1] = {.name="Master Ball", .filename="master-ball.png"},
	[2] = {.name="Ultra Ball", .filename="ultra-ball.png"},
	[3] = {.name="Great Ball", .filename="great-ball.png"},
	[4] = {.name="Poke Ball", .filename="poke-ball.png"},
	[5] = {.name="Town Map", .filename="town-map.png"},
	[6] = {.name="Bicycle", .filename="bicycle.png"},
	[8] = {.name="Safari Ball", .filename="safari-ball.png"},
	[10] = {.name="Moon Stone", .filename="moon-stone.png"},
	[11] = {.name="Antidote", .filename="antidote.png"},
	[12] = {.name="Burn Heal", .filename="burn-heal.png"},
	[13] = {.name="Ice Heal", .filename="ice-heal.png"},
	[14] = {.name="Awakening", .filename="awakening.png"},
	[15] = {.name="Parlyz Heal", .filename="parlyz-heal.png"},
	[16] = {.name="Full Restore", .filename="full-restore.png"},
	[17] = {.name="Max Potion", .filename="max-potion.png"},
	[18] = {.name="Hyper Potion", .filename="hyper-potion.png"},
	[19] = {.name="Super Potion", .filename="super-potion.png"},
	[20] = {.name="Potion", .filename="potion.png"},
	[29] = {.name="Escape Rope", .filename="escape-rope.png"},
	[30] = {.name="Repel", .filename="repel.png"},
	[31] = {.name="Old Amber", .filename="old-amber.png"},
	[32] = {.name="Fire Stone", .filename="fire-stone.png"},
	[33] = {.name="Thunder stone", .filename="thunder-stone.png"},
	[34] = {.name="Water Stone", .filename="water-stone.png"},
	[35] = {.name="HP Up", .filename="hp-up.png"},
	[36] = {.name="Protein", .filename="protein.png"},
	[37] = {.name="Iron", .filename="iron.png"},
	[38] = {.name="Carbos", .filename="carbos.png"},
	[39] = {.name="Calcium", .filename="calcium.png"},
	[40] = {.name="Rare Candy", .filename="rare-candy.png"},
	[41] = {.name="Dome Fossil", .filename="dome-fossil.png"},
	[42] = {.name="Helix Fossil", .filename="helix-fossil.png"},
	[43] = {.name="Secret Key", .filename="secret-key.png"},
	[45] = {.name="Bike Voucher", .filename="bike-voucher.png"},
	[46] = {.name="X Accuracy", .filename="x-accuracy.png"},
	[47] = {.name="Leaf Stone", .filename="leaf-stone.png"},
	[48] = {.name="Card Key", .filename="card-key.png"},
	[49] = {.name="Nugget", .filename="nugget.png"},
	[51] = {.name="Poke Doll", .filename="poke-doll.png"},
	[52] = {.name="Full Heal", .filename="full-heal.png"},
	[53] = {.name="Revive", .filename="revive.png"},
	[54] = {.name="Max Revive", .filename="max-revive.png"},
	[55] = {.name="Guard Spec.", .filename="guard-spec.png"},
	[56] = {.name="Super Repel", .filename="super-repel.png"},
	[57] = {.name="Max Repel", .filename="max-repel.png"},
	[58] = {.name="Dire Hit", .filename="dire-hit.png"},
	[60] = {.name="Fresh Water", .filename="fresh-water.png"},
	[61] = {.name="Soda Pop", .filename="soda-pop.png"},
	[62] = {.name="Lemonade", .filename="lemonade.png"},
	[63] = {.name="S.S. Ticket", .filename="ss-ticket.png"},
	[64] = {.name="Gold Teeth", .filename="gold-teeth.png"},
	[65] = {.name="X Attack", .filename="x-attack.png"},
	[66] = {.name="X Defend", .filename="x-defend.png"},
	[67] = {.name="X Speed", .filename="x-speed.png"},
	[68] = {.name="X Special", .filename="x-special.png"},
	[69] = {.name="Coin Case", .filename="coin-case.png"},
	[70] = {.name="Oak's Parcel", .filename="oaks-parcel.png"},
	[71] = {.name="Item Finder", .filename="itemfinder.png"},
	[72] = {.name="Silph Scope", .filename="silph-scope.png"},
	[73] = {.name="Poke Flute", .filename="poke-flute.png"},
	[74] = {.name="Lift Key", .filename="lift-key.png"},
	[75] = {.name="Exp. All", .filename="exp-all.png"},
	[76] = {.name="Old Rod", .filename="old-rod.png"},
	[77] = {.name="Good Rod", .filename="good-rod.png"},
	[78] = {.name="Super Rod", .filename="super-rod.png"},
	[79] = {.name="PP Up", .filename="pp-up.png"},
	[80] = {.name="Ether", .filename="ether.png"},
	[81] = {.name="Max Ether", .filename="max-ether.png"},
	[82] = {.name="Elixer", .filename="elixer.png"},
	[83] = {.name="Max Elixer", .filename="max-elixer.png"},
	[196] = {.name="HM01", .filename="normal.png"},
	[197] = {.name="HM02", .filename="flying.png"},
	[198] = {.name="HM03", .filename="water.png"},
	[199] = {.name="HM04", .filename="normal.png"},
	[200] = {.name="HM05", .filename="normal.png"},
	[201] = {.name="TM01", .filename="normal.png"},
	[202] = {.name="TM02", .filename="normal.png"},
	[203] = {.name="TM03", .filename="normal.png"},
	[204] = {.name="TM04", .filename="normal.png"},
	[205] = {.name="TM05", .filename="normal.png"},
	[206] = {.name="TM06", .filename="poison.png"},
	[207] = {.name="TM07", .filename="normal.png"},
	[208] = {.name="TM08", .filename="normal.png"},
	[209] = {.name="TM09", .filename="normal.png"},
	[210] = {.name="TM10", .filename="normal.png"},
	[211] = {.name="TM11", .filename="water.png"},
	[212] = {.name="TM12", .filename="water.png"},
	[213] = {.name="TM13", .filename="ice.png"},
	[214] = {.name="TM14", .filename="ice.png"},
	[215] = {.name="TM15", .filename="normal.png"},
	[216] = {.name="TM16", .filename="normal.png"},
	[217] = {.name="TM17", .filename="fighting.png"},
	[218] = {.name="TM18", .filename="fighting.png"},
	[219] = {.name="TM19", .filename="fighting.png"},
	[220] = {.name="TM20", .filename="normal.png"},
	[221] = {.name="TM21", .filename="grass.png"},
	[222] = {.name="TM22", .filename="grass.png"},
	[223] = {.name="TM23", .filename="dragon.png"},
	[224] = {.name="TM24", .filename="electric.png"},
	[225] = {.name="TM25", .filename="electric.png"},
	[226] = {.name="TM26", .filename="ground.png"},
	[227] = {.name="TM27", .filename="ground.png"},
	[228] = {.name="TM28", .filename="ground.png"},
	[229] = {.name="TM29", .filename="psychic.png"},
	[230] = {.name="TM30", .filename="psychic.png"},
	[231] = {.name="TM31", .filename="normal.png"},
	[232] = {.name="TM32", .filename="normal.png"},
	[233] = {.name="TM33", .filename="psychic.png"},
	[234] = {.name="TM34", .filename="normal.png"},
	[235] = {.name="TM35", .filename="normal.png"},
	[236] = {.name="TM36", .filename="normal.png"},
	[237] = {.name="TM37", .filename="normal.png"},
	[238] = {.name="TM38", .filename="fire.png"},
	[239] = {.name="TM39", .filename="normal.png"},
	[240] = {.name="TM40", .filename="normal.png"},
	[241] = {.name="TM41", .filename="normal.png"},
	[242] = {.name="TM42", .filename="psychic.png"},
	[243] = {.name="TM43", .filename="flying.png"},
	[244] = {.name="TM44", .filename="psychic.png"},
	[245] = {.name="TM45", .filename="electric.png"},
	[246] = {.name="TM46", .filename="psychic.png"},
	[247] = {.name="TM47", .filename="normal.png"},
	[248] = {.name="TM48", .filename="rock.png"},
	[249] = {.name="TM49", .filename="normal.png"},
	[250] = {.name="TM50", .filename="normal.png"},
};

Info pokemon[] = 
{
	[RHYDON] = {.name="Rhydon", .filename="rhydon.png"},
	[KANGASKHAN] = {.name="Kangaskhan", .filename="kangaskhan.png"},
	[NIDORAN_M] = {.name="Nidoran M", .filename="nidoran-m.png"},
	[CLEFAIRY] = {.name="Clefairy", .filename="clefairy.png"},
	[SPEAROW] = {.name="Spearow", .filename="spearow.png"},
	[VOLTORB] = {.name="Voltorb", .filename="voltorb.png"},
	[NIDOKING] = {.name="Nidoking", .filename="nidoking.png"},
	[SLOWBRO] = {.name="Slowbro", .filename="slowbro.png"},
	[IVYSAUR] = {.name="Ivysaur", .filename="ivysaur.png"},
	[EXEGGUTOR] = {.name="Exeggutor", .filename="exeggutor.png"},
	[LICKITUNG] = {.name="Lickitung", .filename="lickitung.png"},
	[EXEGGCUTE] = {.name="Exeggcute", .filename="exeggcute.png"},
	[GRIMER] = {.name="Grimer", .filename="grimer.png"},
	[GENGAR] = {.name="Gengar", .filename="gengar.png"},
	[NIDORAN_F] = {.name="Nidoran F", .filename="nidoran-f.png"},
	[NIDOQUEEN] = {.name="Nidoqueen", .filename="nidoqueen.png"},
	[CUBONE] = {.name="Cubone", .filename="cubone.png"},
	[RHYHORN] = {.name="Rhyhorn", .filename="rhyhorn.png"},
	[LAPRAS] = {.name="Lapras", .filename="lapras.png"},
	[ARCANINE] = {.name="Arcanine", .filename="arcanine.png"},
	[MEW] = {.name="Mew", .filename="mew.png"},
	[GYARADOS] = {.name="Gyarados", .filename="gyarados.png"},
	[SHELLDER] = {.name="Shellder", .filename="shellder.png"},
	[TENTACOOL] = {.name="Tentacool", .filename="tentacool.png"},
	[GASTLY] = {.name="Gastly", .filename="gastly.png"},
	[SCYTHER] = {.name="Scyther", .filename="scyther.png"},
	[STARYU] = {.name="Staryu", .filename="staryu.png"},
	[BLASTOISE] = {.name="Blastoise", .filename="blastoise.png"},
	[PINSIR] = {.name="Pinsir", .filename="pinsir.png"},
	[TANGELA] = {.name="Tangela", .filename="tangela.png"},
	[GROWLITHE] = {.name="Growlithe", .filename="growlithe.png"},
	[ONIX] = {.name="Onix", .filename="onix.png"},
	[FEAROW] = {.name="Fearow", .filename="fearow.png"},
	[PIDGEY] = {.name="Pidgey", .filename="pidgey.png"},
	[SLOWPOKE] = {.name="Slowpoke", .filename="slowpoke.png"},
	[KADABRA] = {.name="Kadabra", .filename="kadabra.png"},
	[GRAVELER] = {.name="Graveler", .filename="graveler.png"},
	[CHANSEY] = {.name="Chansey", .filename="chansey.png"},
	[MACHOKE] = {.name="Machoke", .filename="machoke.png"},
	[MR_MIME] = {.name="Mr. Mime", .filename="mr-mime.png"},
	[HITMONLEE] = {.name="Hitmonlee", .filename="hitmonlee.png"},
	[HITMONCHAN] = {.name="Hitmonchan", .filename="hitmonchand.png"},
	[ARBOK] = {.name="Arbok", .filename="arbok.png"},
	[PARASECT] = {.name="Parasect", .filename="parasect.png"},
	[PSYDUCK] = {.name="Psyduck", .filename="psyduck.png"},
	[DROWZEE] = {.name="Drowzee", .filename="drowzee.png"},
	[GOLEM] = {.name="Golem", .filename="golem.png"},
	[MAGMAR] = {.name="Magmar", .filename="magmar.png"},
	[ELECTABUZZ] = {.name="Electabuzz", .filename="electabuzz.png"},
	[MAGNETON] = {.name="Magneton", .filename="magneton.png"},
	[KOFFING] = {.name="Koffing", .filename="koffing.png"},
	[MANKEY] = {.name="Mankey", .filename="mankey.png"},
	[SEEL] = {.name="Seel", .filename="seel.png"},
	[DIGLETT] = {.name="Diglett", .filename="diglett.png"},
	[TAUROS] = {.name="Tauros", .filename="tauros.png"},
	[FARFETCHD] = {.name="Farfetch'd", .filename="farfetchd.png"},
	[VENONAT] = {.name="Venonat", .filename="venonat.png"},
	[DRAGONITE] = {.name="Dragonite", .filename="dragonite.png"},
	[DODUO] = {.name="Doduo", .filename="doduo.png"},
	[POLIWAG] = {.name="Poliwag", .filename="poliwag.png"},
	[JYNX] = {.name="Jynx", .filename="jynx.png"},
	[MOLTRES] = {.name="Moltres", .filename="moltres.png"},
	[ARTICUNO] = {.name="Articuno", .filename="articuno.png"},
	[ZAPDOS] = {.name="Zapdos", .filename="zapdos.png"},
	[DITTO] = {.name="Ditto", .filename="ditto.png"},
	[MEOWTH] = {.name="Meowth", .filename="meowth.png"},
	[KRABBY] = {.name="Krabby", .filename="krabby.png"},
	[VULPIX] = {.name="Vulpix", .filename="vulpix.png"},
	[NINETALES] = {.name="Ninetales", .filename="ninetales.png"},
	[PIKACHU] = {.name="Pikachu", .filename="pikachu.png"},
	[RAICHU] = {.name="Raichu", .filename="raichu.png"},
	[DRATINI] = {.name="Dratini", .filename="dratini.png"},
	[DRAGONAIR] = {.name="Dragonair", .filename="dragonair.png"},
	[KABUTO] = {.name="Kabuto", .filename="kabuto.png"},
	[KABUTOPS] = {.name="Kabutops", .filename="kabutops.png"},
	[HORSEA] = {.name="Horsea", .filename="horsea.png"},
	[SEADRA] = {.name="Seadra", .filename="seadra.png"},
	[SANDSHREW] = {.name="Sandshrew", .filename="sandshrew.png"},
	[SANDSLASH] = {.name="Sandslash", .filename="sandslash.png"},
	[OMANYTE] = {.name="Omanyte", .filename="omanyte.png"},
	[OMASTAR] = {.name="Omastar", .filename="omastar.png"},
	[JIGGLYPUFF] = {.name="Jigglypuff", .filename="jugglypuff.png"},
	[WIGGLYTUFF] = {.name="Wigglytuff", .filename="wigglytuff.png"},
	[EEVEE] = {.name="Eevee", .filename="eevee.png"},
	[FLAREON] = {.name="Flareon", .filename="flareon.png"},
	[JOLTEON] = {.name="Jolteon", .filename="jolteon.png"},
	[VAPOREON] = {.name="Vaporeon", .filename="vaporeon.png"},
	[MACHOP] = {.name="Machop", .filename="machop.png"},
	[ZUBAT] = {.name="Zubat", .filename="zubat.png"},
	[EKANS] = {.name="Ekans", .filename="ekans.png"},
	[PARAS] = {.name="Paras", .filename="paras.png"},
	[POLIWHIRL] = {.name="Poliwhirl", .filename="poliwhirl.png"},
	[POLIWRATH] = {.name="Poliwrath", .filename="poliwrath.png"},
	[WEEDLE] = {.name="Weedle", .filename="weedle.png"},
	[KAKUNA] = {.name="Kakuna", .filename="kakuna.png"},
	[BEEDRILL] = {.name="Beedrill", .filename="beedrill.png"},
	[DODRIO] = {.name="Dodrio", .filename="dodrio.png"},
	[PRIMEAPE] = {.name="Primeape", .filename="primeape.png"},
	[DUGTRIO] = {.name="Dugtrio", .filename="dugtrio.png"},
	[VENOMOTH] = {.name="Venomoth", .filename="venomoth.png"},
	[DEWGONG] = {.name="Dewgong", .filename="dewgong.png"},
	[CATERPIE] = {.name="Caterpie", .filename="caterpie.png"},
	[METAPOD] = {.name="Metapod", .filename="Metapod.png"},
	[BUTTERFREE] = {.name="Butterfree", .filename="butterfree.png"},
	[MACHAMP] = {.name="Machamp", .filename="machamp.png"},
	[GOLDUCK] = {.name="Golduck", .filename="golduck.png"},
	[HYPNO] = {.name="Hypno", .filename="hypno.png"},
	[GOLBAT] = {.name="Golbat", .filename="golbat.png"},
	[MEWTWO] = {.name="Mewtwo", .filename="mewtwo.png"},
	[SNORLAX] = {.name="Snorlax", .filename="snorlax.png"},
	[MAGIKARP] = {.name="Magikarp", .filename="magikarp.png"},
	[MUK] = {.name="Muk", .filename="muk.png"},
	[KINGLER] = {.name="Kingler", .filename="kingler.png"},
	[CLOYSTER] = {.name="Cloyster", .filename="cloyster.png"},
	[ELECTRODE] = {.name="Electrode", .filename="electrode.png"},
	[CLEFABLE] = {.name="Clefable", .filename="clefable.png"},
	[WEEZING] = {.name="Weezing", .filename="weezing.png"},
	[PERSIAN] = {.name="Persian", .filename="persian.png"},
	[MAROWAK] = {.name="Marowak", .filename="marowak.png"},
	[HAUNTER] = {.name="Haunter", .filename="haunter.png"},
	[ABRA] = {.name="Abra", .filename="abra.png"},
	[ALAKAZAM] = {.name="Alakazam", .filename="alakazam.png"},
	[PIDGEOTTO] = {.name="Pidgeotto", .filename="pidgeotto.png"},
	[PIDGEOT] = {.name="Pidgeot", .filename="pidgeot.png"},
	[STARMIE] = {.name="Starmie", .filename="starmie.png"},
	[BULBASAUR] = {.name="Bulbasaur", .filename="bulbasaur.png"},
	[VENUSAUR] = {.name="Venusaur", .filename="venusaur.png"},
	[TENTACRUEL] = {.name="Tentacruel", .filename="tentacruel.png"},
	[GOLDEEN] = {.name="Goldeen", .filename="goldeen.png"},
	[SEAKING] = {.name="Seaking", .filename="seaking.png"},
	[PONYTA] = {.name="Ponyta", .filename="ponyta.png"},
	[RAPIDASH] = {.name="Rapidash", .filename="rapidash.png"},
	[RATTATA] = {.name="Rattata", .filename="rattata.png"},
	[RATICATE] = {.name="Raticate", .filename="raticate.png"},
	[NIDORINO] = {.name="Nidorino", .filename="nidorino.png"},
	[NIDORINA] = {.name="Nidorina", .filename="nidorina.png"},
	[GEODUDE] = {.name="Geodude", .filename="geodude.png"},
	[PORYGON] = {.name="Porygon", .filename="porygon.png"},
	[AERODACTYL] = {.name="Aerodactyl", .filename="aerodactyl.png"},
	[MAGNEMITE] = {.name="Magnemite", .filename="magnemite.png"},
	[CHARMANDER] = {.name="Charmander", .filename="charmander.png"},
	[SQUIRTLE] = {.name="Squirtle", .filename="squirtle.png"},
	[CHARMELEON] = {.name="Charmeleon", .filename="charmeleon.png"},
	[WARTORTLE] = {.name="Wartortle", .filename="wartortle.png"},
	[CHARIZARD] = {.name="Charizard", .filename="charizard.png"},
	[ODDISH] = {.name="Oddish", .filename="oddish.png"},
	[GLOOM] = {.name="Gloom", .filename="gloom.png"},
	[VILEPLUME] = {.name="Vileplume", .filename="vileplume.png"},
	[BELLSPROUT] = {.name="Bellsprout", .filename="bellsprout.png"},
	[WEEPINBELL] = {.name="Weepinbell", .filename="weepinbell.png"},
	[VICTREEBEL] = {.name="Victreebel", .filename="victreebel.png"},
};

static PokemonBaseStats pokemon_stats[] =
{
	[ABRA] = {.hp=25, .attack=20, .defense=15, .speed=90, .special=105, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=200, .growth_rate=MEDIUM_SLOW },
	[AERODACTYL] = {.hp=80, .attack=105, .defense=65, .speed=130, .special=60, .type1=TYPE_ROCK, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=SLOW },
	[ALAKAZAM] = {.hp=55, .attack=50, .defense=45, .speed=120, .special=135, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=50, .growth_rate=MEDIUM_SLOW },
	[ARBOK] = {.hp=60, .attack=85, .defense=69, .speed=80, .special=65, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=90, .growth_rate=MEDIUM_FAST },
	[ARCANINE] = {.hp=90, .attack=110, .defense=80, .speed=95, .special=80, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=75, .growth_rate=SLOW },
	[ARTICUNO] = {.hp=90, .attack=85, .defense=100, .speed=85, .special=125, .type1=TYPE_ICE, .type2=TYPE_FLYING, .catch_rate=3, .growth_rate=SLOW },
	[BEEDRILL] = {.hp=65, .attack=80, .defense=40, .speed=75, .special=45, .type1=TYPE_BUG, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[BELLSPROUT] = {.hp=50, .attack=75, .defense=35, .speed=40, .special=70, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=255, .growth_rate=MEDIUM_SLOW },
	[BLASTOISE] = {.hp=79, .attack=83, .defense=100, .speed=78, .special=85, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[BULBASAUR] = {.hp=45, .attack=49, .defense=49, .speed=45, .special=65, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[BUTTERFREE] = {.hp=60, .attack=45, .defense=50, .speed=70, .special=80, .type1=TYPE_BUG, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[CATERPIE] = {.hp=45, .attack=30, .defense=35, .speed=45, .special=20, .type1=TYPE_BUG, .type2=TYPE_BUG, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[CHANSEY] = {.hp=250, .attack=5, .defense=5, .speed=50, .special=105, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=30, .growth_rate=FAST },
	[CHARIZARD] = {.hp=78, .attack=84, .defense=78, .speed=100, .special=85, .type1=TYPE_FIRE, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[CHARMANDER] = {.hp=39, .attack=52, .defense=43, .speed=65, .special=50, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[CHARMELEON] = {.hp=58, .attack=64, .defense=58, .speed=80, .special=65, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[CLEFABLE] = {.hp=95, .attack=70, .defense=73, .speed=60, .special=85, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=25, .growth_rate=FAST },
	[CLEFAIRY] = {.hp=70, .attack=45, .defense=48, .speed=35, .special=60, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=150, .growth_rate=FAST },
	[CLOYSTER] = {.hp=50, .attack=95, .defense=180, .speed=70, .special=85, .type1=TYPE_WATER, .type2=TYPE_ICE, .catch_rate=60, .growth_rate=SLOW },
	[CUBONE] = {.hp=50, .attack=50, .defense=95, .speed=35, .special=40, .type1=TYPE_GROUND, .type2=TYPE_GROUND, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[DEWGONG] = {.hp=90, .attack=70, .defense=80, .speed=70, .special=95, .type1=TYPE_WATER, .type2=TYPE_ICE, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[DIGLETT] = {.hp=10, .attack=55, .defense=25, .speed=95, .special=45, .type1=TYPE_GROUND, .type2=TYPE_GROUND, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[DITTO] = {.hp=48, .attack=48, .defense=48, .speed=48, .special=48, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=35, .growth_rate=MEDIUM_FAST },
	[DODRIO] = {.hp=60, .attack=110, .defense=70, .speed=100, .special=60, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[DODUO] = {.hp=35, .attack=85, .defense=45, .speed=75, .special=35, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[DRAGONAIR] = {.hp=61, .attack=84, .defense=65, .speed=70, .special=70, .type1=TYPE_DRAGON, .type2=TYPE_DRAGON, .catch_rate=45, .growth_rate=SLOW },
	[DRAGONITE] = {.hp=91, .attack=134, .defense=95, .speed=80, .special=100, .type1=TYPE_DRAGON, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=SLOW },
	[DRATINI] = {.hp=41, .attack=64, .defense=45, .speed=50, .special=50, .type1=TYPE_DRAGON, .type2=TYPE_DRAGON, .catch_rate=45, .growth_rate=SLOW },
	[DROWZEE] = {.hp=60, .attack=48, .defense=45, .speed=42, .special=90, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[DUGTRIO] = {.hp=35, .attack=80, .defense=50, .speed=120, .special=70, .type1=TYPE_GROUND, .type2=TYPE_GROUND, .catch_rate=50, .growth_rate=MEDIUM_FAST },
	[EEVEE] = {.hp=55, .attack=55, .defense=50, .speed=55, .special=65, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[EKANS] = {.hp=35, .attack=60, .defense=44, .speed=55, .special=40, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[ELECTABUZZ] = {.hp=65, .attack=83, .defense=57, .speed=105, .special=85, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[ELECTRODE] = {.hp=60, .attack=50, .defense=70, .speed=140, .special=80, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=60, .growth_rate=MEDIUM_FAST },
	[EXEGGCUTE] = {.hp=60, .attack=40, .defense=80, .speed=40, .special=60, .type1=TYPE_GRASS, .type2=TYPE_PSYCHIC, .catch_rate=90, .growth_rate=SLOW },
	[EXEGGUTOR] = {.hp=95, .attack=95, .defense=85, .speed=55, .special=125, .type1=TYPE_GRASS, .type2=TYPE_PSYCHIC, .catch_rate=45, .growth_rate=SLOW },
	[FARFETCHD] = {.hp=52, .attack=65, .defense=55, .speed=60, .special=58, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[FEAROW] = {.hp=65, .attack=90, .defense=65, .speed=100, .special=61, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=90, .growth_rate=MEDIUM_FAST },
	[FLAREON] = {.hp=65, .attack=130, .defense=60, .speed=65, .special=110, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[GASTLY] = {.hp=30, .attack=35, .defense=30, .speed=80, .special=100, .type1=TYPE_GHOST, .type2=TYPE_POISON, .catch_rate=190, .growth_rate=MEDIUM_SLOW },
	[GENGAR] = {.hp=60, .attack=65, .defense=60, .speed=110, .special=130, .type1=TYPE_GHOST, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[GEODUDE] = {.hp=40, .attack=80, .defense=100, .speed=20, .special=30, .type1=TYPE_ROCK, .type2=TYPE_GROUND, .catch_rate=255, .growth_rate=MEDIUM_SLOW },
	[GLOOM] = {.hp=60, .attack=65, .defense=70, .speed=40, .special=85, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[GOLBAT] = {.hp=75, .attack=80, .defense=70, .speed=90, .special=75, .type1=TYPE_POISON, .type2=TYPE_FLYING, .catch_rate=90, .growth_rate=MEDIUM_FAST },
	[GOLDEEN] = {.hp=45, .attack=67, .defense=60, .speed=63, .special=50, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=225, .growth_rate=MEDIUM_FAST },
	[GOLDUCK] = {.hp=80, .attack=82, .defense=78, .speed=85, .special=80, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[GOLEM] = {.hp=80, .attack=110, .defense=130, .speed=45, .special=55, .type1=TYPE_ROCK, .type2=TYPE_GROUND, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[GRAVELER] = {.hp=55, .attack=95, .defense=115, .speed=35, .special=45, .type1=TYPE_ROCK, .type2=TYPE_GROUND, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[GRIMER] = {.hp=80, .attack=80, .defense=50, .speed=25, .special=40, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[GROWLITHE] = {.hp=55, .attack=70, .defense=45, .speed=60, .special=50, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=190, .growth_rate=SLOW },
	[GYARADOS] = {.hp=95, .attack=125, .defense=79, .speed=81, .special=100, .type1=TYPE_WATER, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=SLOW },
	[HAUNTER] = {.hp=45, .attack=50, .defense=45, .speed=95, .special=115, .type1=TYPE_GHOST, .type2=TYPE_POISON, .catch_rate=90, .growth_rate=MEDIUM_SLOW },
	[HITMONCHAN] = {.hp=50, .attack=105, .defense=79, .speed=76, .special=35, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[HITMONLEE] = {.hp=50, .attack=120, .defense=53, .speed=87, .special=35, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[HORSEA] = {.hp=30, .attack=40, .defense=70, .speed=60, .special=70, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=225, .growth_rate=MEDIUM_FAST },
	[HYPNO] = {.hp=85, .attack=73, .defense=70, .speed=67, .special=115, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[IVYSAUR] = {.hp=60, .attack=62, .defense=63, .speed=60, .special=80, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[JIGGLYPUFF] = {.hp=115, .attack=45, .defense=20, .speed=20, .special=25, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=170, .growth_rate=FAST },
	[JOLTEON] = {.hp=65, .attack=65, .defense=60, .speed=130, .special=110, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[JYNX] = {.hp=65, .attack=50, .defense=35, .speed=95, .special=95, .type1=TYPE_ICE, .type2=TYPE_PSYCHIC, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[KABUTO] = {.hp=30, .attack=80, .defense=90, .speed=55, .special=45, .type1=TYPE_ROCK, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[KABUTOPS] = {.hp=60, .attack=115, .defense=105, .speed=80, .special=70, .type1=TYPE_ROCK, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[KADABRA] = {.hp=40, .attack=35, .defense=30, .speed=105, .special=120, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=100, .growth_rate=MEDIUM_SLOW },
	[KAKUNA] = {.hp=45, .attack=25, .defense=50, .speed=35, .special=25, .type1=TYPE_BUG, .type2=TYPE_POISON, .catch_rate=120, .growth_rate=MEDIUM_FAST },
	[KANGASKHAN] = {.hp=105, .attack=95, .defense=80, .speed=90, .special=40, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[KINGLER] = {.hp=55, .attack=130, .defense=115, .speed=75, .special=50, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=60, .growth_rate=MEDIUM_FAST },
	[KOFFING] = {.hp=40, .attack=65, .defense=95, .speed=35, .special=60, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[KRABBY] = {.hp=30, .attack=105, .defense=90, .speed=50, .special=25, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=225, .growth_rate=MEDIUM_FAST },
	[LAPRAS] = {.hp=130, .attack=85, .defense=80, .speed=60, .special=95, .type1=TYPE_WATER, .type2=TYPE_ICE, .catch_rate=45, .growth_rate=SLOW },
	[LICKITUNG] = {.hp=90, .attack=55, .defense=75, .speed=30, .special=60, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[MACHAMP] = {.hp=90, .attack=130, .defense=80, .speed=55, .special=65, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[MACHOKE] = {.hp=80, .attack=100, .defense=70, .speed=45, .special=50, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=90, .growth_rate=MEDIUM_SLOW },
	[MACHOP] = {.hp=70, .attack=80, .defense=50, .speed=35, .special=35, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=180, .growth_rate=MEDIUM_SLOW },
	[MAGIKARP] = {.hp=20, .attack=10, .defense=55, .speed=80, .special=20, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=255, .growth_rate=SLOW },
	[MAGMAR] = {.hp=65, .attack=95, .defense=57, .speed=93, .special=85, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[MAGNEMITE] = {.hp=25, .attack=35, .defense=70, .speed=45, .special=95, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[MAGNETON] = {.hp=50, .attack=60, .defense=95, .speed=70, .special=120, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=60, .growth_rate=MEDIUM_FAST },
	[MANKEY] = {.hp=40, .attack=80, .defense=35, .speed=70, .special=35, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[MAROWAK] = {.hp=60, .attack=80, .defense=110, .speed=45, .special=50, .type1=TYPE_GROUND, .type2=TYPE_GROUND, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[MEOWTH] = {.hp=40, .attack=45, .defense=35, .speed=90, .special=40, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[METAPOD] = {.hp=50, .attack=20, .defense=55, .speed=30, .special=25, .type1=TYPE_BUG, .type2=TYPE_BUG, .catch_rate=120, .growth_rate=MEDIUM_FAST },
	[MEW] = {.hp=100, .attack=100, .defense=100, .speed=100, .special=100, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[MEWTWO] = {.hp=106, .attack=110, .defense=90, .speed=130, .special=154, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=3, .growth_rate=SLOW },
	[MOLTRES] = {.hp=90, .attack=100, .defense=90, .speed=90, .special=125, .type1=TYPE_FIRE, .type2=TYPE_FLYING, .catch_rate=3, .growth_rate=SLOW },
	[MR_MIME] = {.hp=40, .attack=45, .defense=65, .speed=90, .special=100, .type1=TYPE_PSYCHIC, .type2=TYPE_PSYCHIC, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[MUK] = {.hp=105, .attack=105, .defense=75, .speed=50, .special=65, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[NIDOKING] = {.hp=81, .attack=92, .defense=77, .speed=85, .special=75, .type1=TYPE_POISON, .type2=TYPE_GROUND, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[NIDOQUEEN] = {.hp=90, .attack=82, .defense=87, .speed=76, .special=75, .type1=TYPE_POISON, .type2=TYPE_GROUND, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[NIDORAN_F] = {.hp=55, .attack=47, .defense=52, .speed=41, .special=40, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=235, .growth_rate=MEDIUM_SLOW },
	[NIDORAN_M] = {.hp=46, .attack=57, .defense=40, .speed=50, .special=40, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=235, .growth_rate=MEDIUM_SLOW },
	[NIDORINA] = {.hp=70, .attack=62, .defense=67, .speed=56, .special=55, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[NIDORINO] = {.hp=61, .attack=72, .defense=57, .speed=65, .special=55, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[NINETALES] = {.hp=73, .attack=76, .defense=75, .speed=100, .special=100, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[ODDISH] = {.hp=45, .attack=50, .defense=55, .speed=30, .special=75, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=255, .growth_rate=MEDIUM_SLOW },
	[OMANYTE] = {.hp=35, .attack=40, .defense=100, .speed=35, .special=90, .type1=TYPE_ROCK, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[OMASTAR] = {.hp=70, .attack=60, .defense=125, .speed=55, .special=115, .type1=TYPE_ROCK, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[ONIX] = {.hp=35, .attack=45, .defense=160, .speed=70, .special=30, .type1=TYPE_ROCK, .type2=TYPE_GROUND, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[PARAS] = {.hp=35, .attack=70, .defense=55, .speed=25, .special=55, .type1=TYPE_BUG, .type2=TYPE_GRASS, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[PARASECT] = {.hp=60, .attack=95, .defense=80, .speed=30, .special=80, .type1=TYPE_BUG, .type2=TYPE_GRASS, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[PERSIAN] = {.hp=65, .attack=70, .defense=60, .speed=115, .special=65, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=90, .growth_rate=MEDIUM_FAST },
	[PIDGEOT] = {.hp=83, .attack=80, .defense=75, .speed=91, .special=70, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[PIDGEOTTO] = {.hp=63, .attack=60, .defense=55, .speed=71, .special=50, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[PIDGEY] = {.hp=40, .attack=45, .defense=40, .speed=56, .special=35, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=255, .growth_rate=MEDIUM_SLOW },
	[PIKACHU] = {.hp=35, .attack=55, .defense=30, .speed=90, .special=50, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[PINSIR] = {.hp=65, .attack=125, .defense=100, .speed=85, .special=55, .type1=TYPE_BUG, .type2=TYPE_BUG, .catch_rate=45, .growth_rate=SLOW },
	[POLIWAG] = {.hp=40, .attack=50, .defense=40, .speed=90, .special=40, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=255, .growth_rate=MEDIUM_SLOW },
	[POLIWHIRL] = {.hp=65, .attack=65, .defense=65, .speed=90, .special=50, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[POLIWRATH] = {.hp=90, .attack=85, .defense=95, .speed=70, .special=70, .type1=TYPE_WATER, .type2=TYPE_FIGHTING, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[PONYTA] = {.hp=50, .attack=85, .defense=55, .speed=90, .special=65, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[PORYGON] = {.hp=65, .attack=60, .defense=70, .speed=40, .special=75, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[PRIMEAPE] = {.hp=65, .attack=105, .defense=60, .speed=95, .special=60, .type1=TYPE_FIGHTING, .type2=TYPE_FIGHTING, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[PSYDUCK] = {.hp=50, .attack=52, .defense=48, .speed=55, .special=50, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[RAICHU] = {.hp=60, .attack=90, .defense=55, .speed=100, .special=90, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[RAPIDASH] = {.hp=65, .attack=100, .defense=70, .speed=105, .special=80, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=60, .growth_rate=MEDIUM_FAST },
	[RATICATE] = {.hp=55, .attack=81, .defense=60, .speed=97, .special=50, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=90, .growth_rate=MEDIUM_FAST },
	[RATTATA] = {.hp=30, .attack=56, .defense=35, .speed=72, .special=25, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[RHYDON] = {.hp=105, .attack=130, .defense=120, .speed=40, .special=45, .type1=TYPE_GROUND, .type2=TYPE_ROCK, .catch_rate=60, .growth_rate=SLOW },
	[RHYHORN] = {.hp=80, .attack=85, .defense=95, .speed=25, .special=30, .type1=TYPE_GROUND, .type2=TYPE_ROCK, .catch_rate=120, .growth_rate=SLOW },
	[SANDSHREW] = {.hp=50, .attack=75, .defense=85, .speed=40, .special=30, .type1=TYPE_GROUND, .type2=TYPE_GROUND, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[SANDSLASH] = {.hp=75, .attack=100, .defense=110, .speed=65, .special=55, .type1=TYPE_GROUND, .type2=TYPE_GROUND, .catch_rate=90, .growth_rate=MEDIUM_FAST },
	[SCYTHER] = {.hp=70, .attack=110, .defense=80, .speed=105, .special=55, .type1=TYPE_BUG, .type2=TYPE_FLYING, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[SEADRA] = {.hp=55, .attack=65, .defense=95, .speed=85, .special=95, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[SEAKING] = {.hp=80, .attack=92, .defense=65, .speed=68, .special=80, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=60, .growth_rate=MEDIUM_FAST },
	[SEEL] = {.hp=65, .attack=45, .defense=55, .speed=45, .special=70, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[SHELLDER] = {.hp=30, .attack=65, .defense=100, .speed=40, .special=45, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=190, .growth_rate=SLOW },
	[SLOWBRO] = {.hp=95, .attack=75, .defense=110, .speed=30, .special=80, .type1=TYPE_WATER, .type2=TYPE_PSYCHIC, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[SLOWPOKE] = {.hp=90, .attack=65, .defense=65, .speed=15, .special=40, .type1=TYPE_WATER, .type2=TYPE_PSYCHIC, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[SNORLAX] = {.hp=160, .attack=110, .defense=65, .speed=30, .special=65, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=25, .growth_rate=SLOW },
	[SPEAROW] = {.hp=40, .attack=60, .defense=30, .speed=70, .special=31, .type1=TYPE_NORMAL, .type2=TYPE_FLYING, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[SQUIRTLE] = {.hp=44, .attack=48, .defense=65, .speed=43, .special=50, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[STARMIE] = {.hp=60, .attack=75, .defense=85, .speed=115, .special=100, .type1=TYPE_WATER, .type2=TYPE_PSYCHIC, .catch_rate=60, .growth_rate=SLOW },
	[STARYU] = {.hp=30, .attack=45, .defense=55, .speed=85, .special=70, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=225, .growth_rate=SLOW },
	[TANGELA] = {.hp=65, .attack=55, .defense=115, .speed=60, .special=100, .type1=TYPE_GRASS, .type2=TYPE_GRASS, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[TAUROS] = {.hp=75, .attack=100, .defense=95, .speed=110, .special=70, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=45, .growth_rate=SLOW },
	[TENTACOOL] = {.hp=40, .attack=40, .defense=35, .speed=70, .special=100, .type1=TYPE_WATER, .type2=TYPE_POISON, .catch_rate=190, .growth_rate=SLOW },
	[TENTACRUEL] = {.hp=80, .attack=70, .defense=65, .speed=100, .special=120, .type1=TYPE_WATER, .type2=TYPE_POISON, .catch_rate=60, .growth_rate=SLOW },
	[VAPOREON] = {.hp=130, .attack=65, .defense=60, .speed=65, .special=110, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_FAST },
	[VENOMOTH] = {.hp=70, .attack=65, .defense=60, .speed=90, .special=90, .type1=TYPE_BUG, .type2=TYPE_POISON, .catch_rate=75, .growth_rate=MEDIUM_FAST },
	[VENONAT] = {.hp=60, .attack=55, .defense=50, .speed=45, .special=40, .type1=TYPE_BUG, .type2=TYPE_POISON, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[VENUSAUR] = {.hp=80, .attack=82, .defense=83, .speed=80, .special=100, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[VICTREEBEL] = {.hp=80, .attack=105, .defense=65, .speed=70, .special=100, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[VILEPLUME] = {.hp=75, .attack=80, .defense=85, .speed=50, .special=100, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[VOLTORB] = {.hp=40, .attack=30, .defense=50, .speed=100, .special=55, .type1=TYPE_ELECTRIC, .type2=TYPE_ELECTRIC, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[VULPIX] = {.hp=38, .attack=41, .defense=40, .speed=65, .special=65, .type1=TYPE_FIRE, .type2=TYPE_FIRE, .catch_rate=190, .growth_rate=MEDIUM_FAST },
	[WARTORTLE] = {.hp=59, .attack=63, .defense=80, .speed=58, .special=65, .type1=TYPE_WATER, .type2=TYPE_WATER, .catch_rate=45, .growth_rate=MEDIUM_SLOW },
	[WEEDLE] = {.hp=40, .attack=35, .defense=30, .speed=50, .special=20, .type1=TYPE_BUG, .type2=TYPE_POISON, .catch_rate=255, .growth_rate=MEDIUM_FAST },
	[WEEPINBELL] = {.hp=65, .attack=90, .defense=50, .speed=55, .special=85, .type1=TYPE_GRASS, .type2=TYPE_POISON, .catch_rate=120, .growth_rate=MEDIUM_SLOW },
	[WEEZING] = {.hp=65, .attack=90, .defense=120, .speed=60, .special=85, .type1=TYPE_POISON, .type2=TYPE_POISON, .catch_rate=60, .growth_rate=MEDIUM_FAST },
	[WIGGLYTUFF] = {.hp=140, .attack=70, .defense=45, .speed=45, .special=50, .type1=TYPE_NORMAL, .type2=TYPE_NORMAL, .catch_rate=50, .growth_rate=FAST },
	[ZAPDOS] = {.hp=90, .attack=90, .defense=85, .speed=100, .special=125, .type1=TYPE_ELECTRIC, .type2=TYPE_FLYING, .catch_rate=3, .growth_rate=SLOW },
	[ZUBAT] = {.hp=40, .attack=45, .defense=35, .speed=55, .special=40, .type1=TYPE_POISON, .type2=TYPE_FLYING, .catch_rate=255, .growth_rate=MEDIUM_FAST },
};

static char *moves[] =
{
	[1] = "Pound",
	[2] = "Karate Chop",
	[3] = "Double Slap",
	[4] = "Comet Punch",
	[5] = "Mega Punch",
	[6] = "Pay Day",
	[7] = "Fire Punch",
	[8] = "Ice Punch",
	[9] = "Thunder Punch",
	[10] = "Scratch",
	[11] = "Vice Grip",
	[12] = "Guillotine",
	[13] = "Razor Wind",
	[14] = "Swords Dance",
	[15] = "Cut",
	[16] = "Gust",
	[17] = "Wing Attack",
	[18] = "Whirlwind",
	[19] = "Fly",
	[20] = "Bind",
	[21] = "Slam",
	[22] = "Vine Whip",
	[23] = "Stomp",
	[24] = "Double Kick",
	[25] = "Mega Kick",
	[26] = "Jump Kick",
	[27] = "Rolling Kick",
	[28] = "Sand-Attack",
	[29] = "Headbutt",
	[30] = "Horn Attack",
	[31] = "Fury Attack",
	[32] = "Horn Drill",
	[33] = "Tackle",
	[34] = "Body Slam",
	[35] = "Wrap",
	[36] = "Take Down",
	[37] = "Thrash",
	[38] = "Double-Edge",
	[39] = "Tail Whip",
	[40] = "Poison Sting",
	[41] = "Twineedle",
	[42] = "Pin Missile",
	[43] = "Leer",
	[44] = "Bite",
	[45] = "Growl",
	[46] = "Roar",
	[47] = "Sing",
	[48] = "Supersonic",
	[49] = "Sonic Boom",
	[50] = "Disable",
	[51] = "Acid",
	[52] = "Ember",
	[53] = "Flamethrower",
	[54] = "Mist",
	[55] = "Water Gun",
	[56] = "Hydro Pump",
	[57] = "Surf",
	[58] = "Ice Beam",
	[59] = "Blizzard",
	[60] = "Psybeam",
	[61] = "Bubble Beam",
	[62] = "Aurora Beam",
	[63] = "Hyper Beam",
	[64] = "Peck",
	[65] = "Drill Peck",
	[66] = "Submission",
	[67] = "Low Kick",
	[68] = "Counter",
	[69] = "Seismic Toss",
	[70] = "Strength",
	[71] = "Absorb",
	[72] = "Mega Drain",
	[73] = "Leech Seed",
	[74] = "Growth",
	[75] = "Razor Leaf",
	[76] = "Solar Beam",
	[77] = "Poison Powder",
	[78] = "Stun Spore",
	[79] = "Sleep Powder",
	[80] = "Petal Dance",
	[81] = "String Shot",
	[82] = "Dragon Rage",
	[83] = "Fire Spin",
	[84] = "Thunder Shock",
	[85] = "Thunderbolt",
	[86] = "Thunder Wave",
	[87] = "Thunder",
	[88] = "Rock Throw",
	[89] = "Earthquake",
	[90] = "Fissure",
	[91] = "Dig",
	[92] = "Toxic",
	[93] = "Confusion",
	[94] = "Psychic",
	[95] = "Hypnosis",
	[96] = "Meditate",
	[97] = "Agility",
	[98] = "Quick Attack",
	[99] = "Rage",
	[100] = "Teleport",
	[101] = "Night Shade",
	[102] = "Mimic",
	[103] = "Screech",
	[104] = "Double Team",
	[105] = "Recover",
	[106] = "Harden",
	[107] = "Minimize",
	[108] = "Smokescreen",
	[109] = "Confuse Ray",
	[110] = "Withdraw",
	[111] = "Defense Curl",
	[112] = "Barrier",
	[113] = "Light Screen",
	[114] = "Haze",
	[115] = "Reflect",
	[116] = "Focus Energy",
	[117] = "Bide",
	[118] = "Metronome",
	[119] = "Mirror Move",
	[120] = "Self-Destruct",
	[121] = "Egg Bomb",
	[122] = "Lick",
	[123] = "Smog",
	[124] = "Sludge",
	[125] = "Bone Club",
	[126] = "Fire Blast",
	[127] = "Waterfall",
	[128] = "Clamp",
	[129] = "Swift",
	[130] = "Skull Bash",
	[131] = "Spike Cannon",
	[132] = "Constrict",
	[133] = "Amnesia",
	[134] = "Kinesis",
	[135] = "Soft-Boiled",
	[136] = "Hi Jump Kick",
	[137] = "Glare",
	[138] = "Dream Eater",
	[139] = "Poison Gas",
	[140] = "Barrage",
	[141] = "Leech Life",
	[142] = "Lovely Kiss",
	[143] = "Sky Attack",
	[144] = "Transform",
	[145] = "Bubble",
	[146] = "Dizzy Punch",
	[147] = "Spore",
	[148] = "Flash",
	[149] = "Psywave",
	[150] = "Splash",
	[151] = "Acid Armor",
	[152] = "Crabhammer",
	[153] = "Explosion",
	[154] = "Fury Swipes",
	[155] = "Bonemerang",
	[156] = "Rest",
	[157] = "Rock Slide",
	[158] = "Hyper Fang",
	[159] = "Sharpen",
	[160] = "Conversion",
	[161] = "Tri Attack",
	[162] = "Super Fang",
	[163] = "Slash",
	[164] = "Substitute",
	[165] = "Struggle",
};

Info get_item_info(int id)
{
	return items[id];
}

Info get_pokemon_info(int id)
{
	return pokemon[id];
}

PokemonBaseStats get_pokemon_base_stats(int id)
{
	return pokemon_stats[id];
}

char *get_move_name(int id)
{
	return moves[id];
}

// there are gaps in the pokemon ids that need to be skipped over
int get_pokemon_translated_id(int id)
{
	int translated_id;
	for(translated_id = 1;; translated_id++)
	{
		if(get_pokemon_info(translated_id).name && --id == 0)
				break;
	}

	return translated_id;
}

int get_move_translated_id(int id)
{
	if(id == 0)
		return id;

	int translated_id;
	for(translated_id = 1;; translated_id++)
	{
		if(get_move_name(translated_id) && --id == 0)
			break;
	}

	return translated_id;
}
